{
	"version": 1718304267,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/tiledbackground.png",
		"images/sprite4-sheet0.png",
		"images/sonic-sheet0.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/tiledbackground4.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite15-sheet1.png",
		"images/sprite17-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/sprite25-sheet0.png",
		"images/tiledbackground5.png",
		"media/sonic-the-hedgehog-_-musica-de-fundo_.m4a",
		"media/sonic-the-hedgehog-_-musica-de-fundo_.ogg",
		"media/som-de-moeda-do-sonic-mp3-_128_ (1).m4a",
		"media/som-de-moeda-do-sonic-mp3-_128_ (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}